lib/zookeeper.js
src/node-zk.cpp

Hi,
In cluster mode, to be sure to have the latest update in one node, the sync call is needed. 
so i implemented it :)

Add sync api call

---

package.json
src/buffer_compat.h
src/node-zk.cpp

These changes adopt the latest version of 'nan' which includes support for node 4.x.  I'll run with the changes in our project for a couple of days and then merge if no issues arise.
This will fix #114

Node 4.0 support

---

patches/ZOOKEEPER-642.patch
scripts/env.sh

https://issues.apache.org/jira/browse/ZOOKEEPER-642

Apply ZOOKEEPER-642 to reduce amount of Deadline exceeded warnings

---

CODE-OF-CONDUCT.md

Added code of conduct stating standard community guidelines, and referring any issues to yurif2003 at yahoo dot com.
For issue #160

Add CODE-OF-CONDUCT

---

.npmignore

delete .npmignore file

---

CHANGELOG.md
package.json

Bumped the version. Added changes in the changelog.

Bump version and changelog

---

lib/index.js
lib/typedefs.js
lib/zk_promise.js
lib/zookeeper.js
tests/helpers/fakes.js
tests/zookeeper/exportedconstantstest.js
tests/zookeeper/nativeobjecttest.js
tests/zookeeper/proxypropertiestest.js

This PR includes code comments mainly for type definitions of parameters and return types.
This will make the developer experience a bit better.
Travis CI passed.
Modified the exported constants unit test.

Documentation for public API

---

README.md
examples/addlistener.js
examples/addtask.js
examples/createnode.js
examples/createworker.js
examples/electleader.js
examples/index.js
examples/setup.js
examples/wrapper.js
lib/zk_promise.js

Simplified README file. Changed the recommended usage to a `promise` based client. 
Refactored the code in the `examples` folder to promise based.
To simplify the documentation, and remove text that is no longer relevant.
Issue #166 
Travis CI Build and manual run of the examples code: `node examples/index.js`

Readme revision and example code refactorings

---

CHANGELOG.md
package.json

Bump version.
Changelog.
To package a new release to NPM.
Travis CI Build OK.

4.3.0 release

---

lib/zk_promise.js

Fixed typos in jsDoc comments.

fix: typo in comments

---

lib/promise.js
lib/zk_promise.js
lib/zookeeper.js

Add missing ES201x docs
To make a better developer experience: type hints in the IDE.

fix: add missing docs

---

package.json

Bumped version and info about supported ZooKeeper versions.
To be able to package a new release to `npm`.
Travis Build CI Ok

Package version 4.4.0

---

CHANGELOG.md
README.md
package.json

Bump version, changelog and add @jbienkowski311 to the contributors list!

Release 4.4.1

---

CHANGELOG.md
package.json

chore: bump version, changelog

---

CHANGELOG.md
package.json

feat: bump version, add changelog

---

examples/index.js
lib/constants.js
lib/promise.js
lib/zookeeper.js
package.json
tests/unit/util/promisetest.js
tests/unit/zookeeper/nativeobjecttest.js

Updated dependencies and code according to new lint rules.
`npm install` caused audit warnings: `found 15 vulnerabilities (11 low, 4 high)`
`npm run lint` passed
`npm test` passed
Ran the examples according to https://github.com/yfinkelstein/node-zookeeper/tree/master/examples#examples
Ran the integration tests according to https://github.com/yfinkelstein/node-zookeeper/tree/master/tests/integration
Travis-CI build passed

Update dependencies causing audit warnings on install

---

CHANGELOG.md
package.json

Prepare for release 4.5.3

---

.travis.yml

Run build in a Node.js 14 environment
feat(travisCI): add nodejs 14 build target
Node.js 14 will be the next LTS version, and a passing build step will ensure node-zookeeper can be used in that version to.
Travis CI build OK
Solves https://github.com/yfinkelstein/node-zookeeper/issues/244

Support for Node.js 14

---

examples/wrapper.js
lib/constants.js
lib/index.js
lib/promise.js
lib/typedeclarations.d.ts
lib/typedefs.js
lib/zk_promise.js
lib/zookeeper.js
package.json
tsconfig.json

Include a TypeScript declaration file with the npm package.
Also: fix bugs in code docs (replace wrong JSDoc tags)
A TS declaration file with type hints can improve the developer experience.
`npm test`
`Travis CI build ok`
✅  VS Code
✅ Emacs
~~I haven't yet verified the type hinting by installing the package in an app and writing code. Will use VS Code and Emacs for that.~~

Add TypeScript declarations 

---

CHANGELOG.md
README.md
package.json

feat: bump package version, update documentation

---

package.json

Release a beta version as a first step, verifying the prebuilds are working for users of various systems.

release 4.7.0-beta.0

---

README.md

Note about rejecting/erroring when path does not exist in exists() calls

---

CHANGELOG.md
lib/typedeclarations.d.ts
lib/zk_promise.js
package.json

Fixes https://github.com/yfinkelstein/node-zookeeper/issues/257

fix: wrong type for watch param - should be boolean

---

.circleci/config.yml
.eslintignore
.eslintrc.json
lib/helper.js
package.json
tests/unit/.eslintrc.json

Use the latest version of the Ava testing tool.
It turns out that some things aren't compatible between Ava and the ESLint rules from AirBnb. I will post an issue to Ava about this.
Adjusted the rules (and found a lint error) to make the tools play nice with each other.
Also: split the `npm scripts` into separate parts. Adjusted the CircleCI config according to the script changes.
Using the latest (breaking) version to avoid issues in the future. This is a dev dependency.
npm lint
npm test
npm build-components
npm test-components
CircleCI passed

Use Ava v4

---

examples/exists.js

Bug fix when running more than one node process at the same time.

fix(examples): create unique named temp nodes

---

CHANGELOG.md

add v.6.2.0 changelog

---

CHANGELOG.md
README.md
examples/acl.js
lib/typedeclarations.d.ts
lib/typedefs.js
package.json

Fixing typos in the ACL type definition.
Fixes #194 
✅ CI
✅ Adding a runnable example for ACL.

fix: ACL type defs

---

CHANGELOG.md
package.json

Bump version to 6.2.2.
Pull Request #347 
n/a

bump version to 6.2.2 + changelog

---

CHANGELOG.md
lib/zk_promise.js
package.json

Bump version to 6.2.3
Add changelog
fix: remove unused import
✅ CI

release v 6.2.3
