- binding.gyp
- package.json
- src/buffer_compat.h
- src/node-zk.cpp
- test/zk_test_mkdirp.js
This branch includes the adoption of the 'nan' library so that both 0.10 and 0.12 node versions can be supported at once.  
I've intentionally broken up the adoption into many different commits, so that a reviewer can follow my adoption strategy.  At each step, the code continues to compile with 0.10 and slowly reduces compile errors in 0.12.  At the end, the the commits, both compile cleanly.
This branch fixes #108
> Support node 0.12

- package.json
- src/node-zk.cpp
Do not double initailize a uv_poll_t structure and always close handles before deletion
Fixes #133
> Don't corrupt memory

- .travis.yml
- package.json
- src/node-zk.cpp
Running `npm install` fails when using Node version 10. (v10.11.0).
This Pull Request fixes the issues with the removed `v8_debug.h` and warnings from npm about old packages.
Also, I have replaced the deprecated `ForceSet` with `DefineOwnProperty` according to conversations in the Nan repo, issue https://github.com/nodejs/nan/issues/707
> Node.js 10 support

- scripts/prepublish.js
> fix missing to install on Windows 7

- README.md
The example code use a `connect` function that is not documented in the README. README was edited to add this documentation
Resolves #168
> Added documentation for "connect" function

- lib/zookeeper.js
As the `__defineGetter__`/`__defineSetter__` is being deprecated, I'm going to replace it with [Object.defineProperties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties).
This PR addresses Issue #149.
```
npm test
npm run integrationtest
```
> Refactor deprecated JavaScript gettter/setter feature

- README.md
- scripts/build.js
Reduces amount of output logs produced by `configure` and `make` commands during the build process.
Please see corresponding issue #182 for more information.
`npm install` -> produces less output
`ZK_INSTALL_VERBOSE=1 npm install` -> produces full output
> Reduce build output on Unix systems

- README.md
- patches/CMakeLists.txt
- scripts/prepublish.js
This PR will enable a quicker build experience for Windows users. It will bypass CMake feature checks and will also hide compiler warnings in the output, by overwriting the default `CMakeLists.txt`. 
There is an option to still use the default, by passing in the `ZK_INSTALL_VERBOSE` flag as described [here](https://github.com/yfinkelstein/node-zookeeper#development).
To improve the developer experience on the Windows platform. 
Fixes issue #182 
Travis CI build passed (Windows, Linux, Mac OS X)
Manual `npm install` in a Windows 10 virtual machine.
> Windows: quicker build

- lib/typedefs.js
- lib/zk_promise.js
- lib/zookeeper.js
The type definitions in this PR will help to make the developer experience better. When using an IDE or editor that can interpret the definitions, typing API calls will display expected params and data types. Also callback signatures and complex Promise resolution types! 
An example: hit CTRL + space in WebStorm to get the type information of an API method.
This will likely help developers understand the API a little better.
Solves issue #195 
Travis CI Build passed
Created a new blank project with `npm init` and `npm install davidvujic/node-zookeeper#jsdoc_types`. Created a new JavaScript file with WebStorm that comsumes the library API.
> jsDoc type definitions

- scripts/helper.js
- scripts/prepublish.js
Occasionally, the download of the ZooKeeper source code fails due to timeout and probably more often if behind a proxy. Lately, failing downloads happen quite often in Travis CI. This PR includes a retry feature and extra checks on objects during download. If the download has failed, the install script will try once again.
The error:
```bash
file.unlink is not a function
Unable to download zookeeper library. Error: connect ETIMEDOUT <ip-address-masked>:80
```
Solves failing `npm install`
Fixes issue #201 
Travis CI Build OK
`npm test`
> Retry download if failed

- README.md
- lib/zk_promise.js
the `get_children2` and `w_get_children2` methods of the promisified zookeeper client should return both an array of children __and__ stats. The promisified version only returns the array.
This bug should be fixed, because of the new recommendation to use promises/async/await instead of callbacks.
Fixes issue #203 
Travis CI build OK.
`npm test`
`node examples/index.js`
~~TODO: run the "old" version (pre ES 201x) to verify the API/not working API.~~
> fix: handle multiple return values in promisified client

- .travis.yml
- Dockerfile.gcc
- binding.gyp
- scripts/build.js
Newer versions of gcc warns about code in the ZooKeeper C Client, and by default treat warnings as errors. This will break builds, unless passing a specific flag as described in issue #154 
Also, gcc 9 will warn about code existing in nan.h and v8.h. That is why warnings are disabled for the c++ wrapper code (in binding.gyp).
Users with the latest version of gcc will be able to run `npm install`.
Fixes issue #154 
Travis CI Build Ok
Build passed in a Dockerfile, using gcc 8.3.0 and 9
> Disable warnings as errors when compiling C and C++ code

- scripts/build.js
By default, building on Windows will be less verbose. There's still a couple of warnings there, and should be fixed in a separate PR.
To increase the developer experience on Windows.
Travis CI Build OK
Ran `npm install` on a Windows 10 VM manually (both with and without the verbose flag set).
> fix: less verbose Windows builds

- README.md
- lib/zookeeper.js
- package.json
- tests/unit/zookeeper/nativeobjecttest.js
Fix bug in method "add_auth".
`Error: expected 3 arguments`
> fix bug "expected 3 arguments"

- .gitignore
- README.md
- lib/zk_promise.js
- lib/zookeeper.js
- package.json
- src/converters.hpp
- src/node-zk.cpp
Exposes the dynamic reconfiguration methods from the core ZooKeeper API to the top level JavaScript ZooKeeper class.
Exposes the following methods to the ZooKeeper class as both async and callback funtions:
`zoo_agetconfig`
`zoo_awgetconfig`
`zoo_areconfig`
The following only has one variant as it's a syncronous function
`zoo_setservers`
Also expose the `ZOO_CONFIG_NODE` constant
These allow the user to implement client side dynamic reconfiguration support.
Adds Dynamic Reconfiguration support to the client
https://github.com/yfinkelstein/node-zookeeper/issues/208
Tested in an external command line ZooKeeper client application that uses this module and implements a full client Dynamic Reconfiguration workflow. Also tested unauthenticated reconfiguration from the same client app. …
> Dynamic Reconfiguration

- README.md
- src/node-zk.cpp
Library returns error "zookeeper_process returned no response too many times: 11".
We wanted to add a flag using which will be possible to overwrite the default response counter limit (10).
We have nodes in ZK with a lot of data and the server responds after a couple more tries than 10, about ~40.
Changed value of a new flag "response_counter_limit" to "100" and data was received.
> ability to overwrite default response counter limit (10)

- CONTRIBUTING.md
- package.json
- tests/components/converterstest.js
- tests/unit/index/apitest.js
- tests/unit/index/configtest.js
- tests/unit/index/encodingtest.js
- tests/unit/index/loggertest.js
- tests/unit/util/helpertest.js
- tests/unit/util/promisetest.js
- tests/unit/zookeeper/exportedconstantstest.js
- tests/unit/zookeeper/nativeobjecttest.js
- tests/unit/zookeeper/proxypropertiestest.js
Solves https://github.com/yfinkelstein/node-zookeeper/issues/276
Both `tape` and `tap-spec` seems to be not longer maintained. `tap-spec` has raised npm audit warnings.
A simple solution is to use `Ava` instead, a tool that is actively maintained.
npm run test-unit
npm run test-components
- [ x] I have updated the documentation accordingly (if applicable).
> fix: solve npm audit issues by replacing tape and tap-spec with Ava

- README.md
- examples/exists.js
- examples/index.js
- lib/typedeclarations.d.ts
- lib/zk_promise.js
Fixes issue #254 
Avoiding a breaking change in the existing `exists` function, by adding a `pathExists` that will return a boolean value.
`true` if the path exists, `false` if not.
`npm test` ok.
Added code to the `examples`, that runs the new functions.
CircleCI builds passed.
> feat: add a Boolean "path exists" function

- README.md
- examples/addtask.js
- examples/exists.js
- lib/helper.js
- lib/zk_promise.js
- tests/unit/util/helpertest.js
Explicit checks for errors by validating the result code coming from the C Client.
All calls to methods in the promisified version of the JavaScript client has now an explicit result code check. A result code that has a negative value is a failure, and the method will from now on perform a `reject`.
Before this, errors failed silently, as described in issue #237 - the issue is about the `set` method, but the error exists in all promisified method calls.
fixes #237 
npm tests passed
CircleCI passed
added example code that verifies the behaviour.
> fix: explicitly handle async JavaScript failures.

- lib/helper.js
- lib/zookeeper.js
- package.json
- tests/components/converterstest.js
- tests/integration/getAndSettest.js
- tests/integration/getChildrentest.js
- tests/integration/makeAndDeleteDirtest.js
- tests/integration/sessiontest.js
- tests/unit/index/apitest.js
- tests/unit/index/configtest.js
- tests/unit/index/encodingtest.js
- tests/unit/index/loggertest.js
- tests/unit/util/helpertest.js
- tests/unit/util/promisetest.js
- tests/unit/zookeeper/exportedconstantstest.js
- tests/unit/zookeeper/nativeobjecttest.js
- tests/unit/zookeeper/proxypropertiestest.js
Less depencencies.
Replaced lodash with vanilla JavaScript. 
NOTE: the `_.defaults` lodash function is replaced with `Object.assign` (src and target flipped) to have a similar behaviour as the lodash function. But it isn't 100% the same. If the original object has a key with an `undefined` value, it will behave differently. 
Removed unused deps to `proxyquire` and `ava-eslint-plugin`.
Removed unnecessary usage of the `Ava` function `t.plan()`, according to the [Ava guidelines.](https://github.com/avajs/ava/blob/main/docs/recipes/when-to-use-plan.md)
Less dependencies is also less MB in the node_modules folder. This will make room for some more prebuilds (that are quite heavy).
Fixes #299 
npm test ✅ 
npm run lint ✅ 
npm run test-integration ✅ 
npm run test-components ✅ 
CircleCI ✅
> Replace lodash with vanilla js and remove unused dependencies

- package.json
Remove `node-gyp` from dependencies.
`node-gyp` is already included in Node/npm and `node-gyp-build` uses that one, so does `prebuildify` (if there isn't any other version specified locally). See [Q&A about it here](https://github.com/prebuild/node-gyp-build/issues/41).
Less dependencies, will produce less weight in the `node_modules` folder and will probably speed up the install process.
npm test ✅ 
npm run test-components ✅ 
npm run test-integration ✅ 
CircleCI ✅
> fix: node-gyp is included in npm already

- lib/typedeclarations.d.ts
- lib/zk_promise.js
Fixed incorrect type definitions for the `get` and `w_get` functions.
Fixes #304 
CircleCI ✅ 
npm test ✅
> fix: get functions returns an array of [stat, string|Buffer]

- lib/zookeeper.js
Fixed that the normalize method in the Windows environment changed the separator of the path
on windows platform
normalize("/service/helloservice/consumer") returns “\\\service\\\helloservice\\\consumer”
it will cause slice to return an empty array
> fixed windows path normalize / => \\

- src/node-zk.cpp
replace all `uv_default_loop()` by `Nan::GetCurrentEventLoop()`
here's [GetCurrentEventLoop](https://github.com/nodejs/nan/blob/8db8c8f544f2b6ce1b0859ef6ecdd0a3873a9e62/nan.h#L653) source code
Related to #281 
The problem is uv_default_loop() return the main Node thread when program started, not the Worker's Event Loop in its isolated environment
same as #281
> fix: Cannot start the zookeeper client in a Node.js Worker thread

- deps/no-fipsmode.patch
- scripts/env.js
- scripts/prepublish.js
As FIPS_mode is only used to conditionally print an info message this may be a reasonable fix for #318 
A mechanism to apply patches, in this case used to remove a problematic line of code from the source C files.
See #318
It builds, installs and runs now
> fix: remove code using FIPS_mode which is not available on all distros

- CHANGELOG.md
- README.md
- package.json
The docs and the npm package description was not correct when stating the supported version of Apache ZooKeeper server.
Fixed in this PR.
CircleCI tests passed.
> set the correct supported version of zookeeper server

- README.md
Removing the "news" section of the README.
The changes were made several versions ago.
More importantly: the SSL support announced is not correct. There is need of development to support this. See discussion in #315
> docs: remove news section, and the misleading SSL support announcement.

- package.json
- src/node-zk.cpp
- tests/components/README.md
Replacing a removed V8 AccessControl enum property to the `DEFAULT`.
Details about the enum here:
https://v8docs.nodesource.com/node-20.3/d2/dc3/namespacev8.html#a2e9a0288e6c2df2ecebc50944c3ff9fa
Fixing #343 
✅ CI
✅ Unit tests, integration tests, component tests
> fix: build error in Node.js 22 caused by removed V8 AccessControl property

- README.md
Update Readme to use constants from Zookeeper.constants.*
Since accessing constants directly from Zookeeper is deprecated, it is necessary to update the readme document to use constants from ZooKeeper.constants.*
Readme document still uses a deprecated way to access Zookeeper constants.
Not needed
> docs: access Zookeeper constants from ZooKeeper.constants

- lib/helper.js
- lib/typedeclarations.d.ts
- lib/typedefs.js
- lib/zk_promise.js
- lib/zookeeper.js
- src/node-zk.cpp
- tests/integration/getAndSetAcltest.js
- tests/unit/util/helpertest.js
Accept both perm and perms while creating an acl object
Accept both perm and perms in acl objects while setting acl for a zookeeper node
get_acl returns acl objects with **perms** key, while set_acl accepts only **perm** key, these need to be consistent, so updated the code to take both, so there is no any breaking change and it's consistent.
Added an integration test: [tests/integration/getAndSetAcltest.js](tests/integration/getAndSetAcltest.js)
> Accept both perm and perms in acl objects

- package.json
- src/node-zk.cpp
Enable Workers, by using the Nan worker replacement for. `NODE_MODULE`.
**NOTE:** this is a beta release. Use with Node.js v22 to force the building of the add-on when running `npm install` (v20 has prebuilds already for Mac OS X and Windows, and this change is not in the prebuilds yet).
The soulution was found here:
https://github.com/nktnet1/easy-libcurl/pull/66
https://github.com/nodejs/nan/issues/844
and
https://github.com/nodejs/nan/blob/9585023a32bf0e945c932200fc7f1ddbcf1fadad/CHANGELOG.md?plain=1#L88C14-L88C85
Adresses the issues raised in #314 
✅ CI
✅ local build and run `node examples/index.js`
> feat(beta): enable workers
